import = [ "/home/meet/personal/themes/alacritty-theme/themes/terminal_app.toml",]

[shell]
program = "/bin/zsh"
args = [ "--login", "-c", "/home/meet/personal/git/dotfiles/alacritty/ch-theme", "/bin/zsh",]

[env]
TERM = "xterm-256color"

[window]
decorations = "Buttonless"
opacity = 0.9
blur = true

[font]
size = 23

[window.padding]
x = 10
y = 10

[font.normal]
family = "Hasklug Nerd Font Mono"
