[env]
TERM = "xterm-256color"

[window]
decorations = "Buttonless"
opacity = 0.9
blur = true

[font]
size = 15.5

[general]
import = [ "/home/mpatel/develop/themes/alacritty-theme/themes/catppuccin.toml",]

[window.padding]
x = 10
y = 10

[font.normal]
family = "Hasklug Nerd Font Mono"

[terminal.shell]
program = "/bin/zsh"
args = [ "--login", "-c", "/home/mpatel/develop/dotfiles/alacritty/theme.sh",]

[cursor.style]
shape = "Underline"
