# clone alacritty-theme/ from git
import = [
    "~/personal/themes/alacritty-theme/themes/catppuccin_mocha.toml"
]

[env]
TERM = "xterm-256color"

[window]
padding.x = 10
padding.y = 10

decorations = "Buttonless"

opacity = 0.9
blur = true

[font]
normal.family = "Hasklug Nerd Font Mono"
#normal.family = "Hurmit Nerd Font Mono"
size = 23
