#!/usr/bin/python3

import random
import toml
import os
import sys


def gen_num(list_length):
    return random.randint(0, list_length)

home_dir = str(os.getenv("HOME"))

base_path = home_dir + "/develop/themes/alacritty-theme/themes/"

theme = ""
if (len(sys.argv) < 2):
    files = os.listdir(base_path)
    random_number = gen_num(len(files))
    theme = files[random_number]
    print(f"Random theme - {theme}")
elif (sys.argv[1] == "-m"):
    theme = os.popen(f"ls -la {home_dir}/develop/themes/alacritty-theme/themes | rev | cut -d \" \" -f 1 | rev | fzf").read()
    theme = theme.strip().split()[0]
    print(f"Selected theme - {theme}")
else:
    theme = sys.argv[1]
    print(f"Selected theme - {theme}")

config_file = f'{home_dir}/develop/dotfiles/alacritty/alacritty.toml'
with open(config_file, 'r') as toml_config:
    config = toml.load(toml_config)
    config['general']['import'] = [base_path + theme]

new_config_file = f'{home_dir}/develop/dotfiles/alacritty/new_alacritty.toml'
with open(new_config_file, 'w') as new_toml_config:
    toml.dump(config, new_toml_config)

backup_config_file = f'{home_dir}/develop/dotfiles/alacritty/alacritty-bak.toml'
os.popen(f"cp {config_file} {backup_config_file}").read()
os.popen(f"mv {new_config_file} {config_file}").read()
