#!/usr/bin/env bash
#sudo dnf copr enable solopasha/hyprland -y
#sudo dnf install -y $(cat packages)
#sudo dnf install -y $(cat hypr-packages)
#sudo dnf copr enable scottames/ghostty
#sudo dnf install ghostty

#sudo dnf remove kitty wofi -y

if [ ! -d ~/.tmux/plugins/tpm ]; then
  echo "Installing Tmux plugin manager"
  git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm
else
  echo "Skipping Tmux plugin manager installation"
fi

